Fix #49: check if callable is method
dsa-ou/algoesup pull request #50
Opened 2024-11-18 17:20 UTC by densnow

2024-11-19 12:47 UTC, mwermelinger commented
Thanks, @densnow. Could you also add some tests to test `test()`? At the moment, we test algoesup by running the example essays, but those are limited, e.g. have no wrong test tables. It would be nice to have a better/quicker way of testing the algoesup library, preferably automated. That will be quite some effort, so for the moment it would be enough to have a simple Python program (in a `tests` folder) that when run (by `pytest` for example) simply calls `test()` on a function and a method, with good and bad test tables to check that `test()` reports ill-formatted test tables. 

No need for a new issue or PR. This one will do. Thanks.

2024-11-20 12:40 UTC, densnow commented
@mwermelinger I've added some files for automated testing with `pytest`. The strategy is to have functions and methods defined in `callables.py` that return the sum of their args for easy creation of test tables. Then in `test_test.py` (bit of a silly name!) , I've set up some utility functions to help "easily" write test cases. The actual testing uses capsys to capture the output from `algoesup.test` and sees if the expected output string is present in this output.

When writing the test cases, I realised we had not considered functions/methods which accept a variable number of arguments (*args, **kwargs and default args) . Hence `algoesup.test` has been modified to skip the number of args comparison if a function or method accepts a variable number of args.

I've just written a small number of basic test cases to get started, but we might need a few more to be completely covered.

To run the tests, do a `poetry install` followed by a `poetry run pytest` in the root directory.

2024-11-22 09:49 UTC, mwermelinger requested changes
Many thanks! It's more complicated than I expected, well done. One query: why can't built-ins be tested? I know I added that to the docstring myself, but can't remember why. I commented out the `if isbuiltin...` and then doing 

`test(abs, [("negative", -3, 3)])` 
`test(sum, [("ok", [-3, 0, 5], 2), ("wrong", [-3, 5], -2)])` 

works fine. However,  `test(sum, [("", -3, 0, 5, 2)])` doesn't detect that sum is being called with 3 instead of just two parameters, and therefore does `actual = function(*args)` which then makes Python crash for that reason. Sum takes one iterable and one keyword arg with default value, so unsure why it's not detecting.

will crea

2024-11-22 12:10 UTC, densnow commented
>One query: why can't built-ins be tested? I know I added that to the docstring myself, but can't remember why.

I believe this was because of not being able to get reliable metadata about arguments see [this note in the inspect documentation](https://docs.python.org/3/library/inspect.html#:~:text=Note%20Some%20callables%20may%20not%20be%20introspectable%20in%20certain%20implementations%20of%20Python.%20For%20example%2C%20in%20CPython%2C%20some%20built%2Din%20functions%20defined%20in%20C%20provide%20no%20metadata%20about%20their%20arguments.). Looking at it from fresh perspective now, it would make more sense to treat built-ins in the same way a callables with variable numbers of args and just skip the argument number checks for them?

On a different note: how do you feel about having all the test data in one table and only using one testing function? For some reason I wasn't entirely comfortable with that, but when I tried splitting the data and using multiple testing functions it seemed like they were just doing the same thing.

2025-01-02 15:57 UTC, mwermelinger commented
Happy new year, @densnow! I'm looking at this again (sorry for the delay) and wonder if the algorithm could be simplified like this: 

Check if the table is tuple or list, and stop it if isn't. 
Otherwise go through each test and report it as invalid if it's not a list or tuple, has length < 2, or doesn't start w/ a string, w/ appropriate error message, but continue.
Otherwise attempt to run the test, and report it as failed if it raises an exception, printing "{name} FAILED: {exception msg}". 
At the end, print number of passed, failed and invalid tests.

I think this is more flexible, because even if the number of parameters match, the function call can still crash. We can still check parameter numbers for those without variable args,
and report it as invalid test. We probably need to silently ignore any exception raised by inspect.signature. 

Let me know what you think and if you foresee this breaking existing use of algoesup.test in TMAs and book.

2025-01-02 16:25 UTC, mwermelinger commented
Will it be confusing for students to report wrong number of parameters as invalid test, if args are fixed, and as failed test otherwise?

Anyhow, the docstring and coding.ipynb will have to be updated.

2025-01-02 17:51 UTC, densnow commented
Happy new year @mwermelinger. The original thinking was that any invalid test cases would lead to "pulling the plug", and not doing any tests: when this happens, make it clear to students which case was invalid, and that the function has not been fully tested. Having some tests pass, some fail and some invalid certainly has the potential to confuse, and possibly lead to students falsely thinking their algorithm is working or not working. Having said all that, showing a student which cases are valid and which are not might help them fix the issue, the advantage would be that all valid test cases would be shown in contrast to only showing one/some of the invalid case(s). I'm not sure how much of an advantage this is though.

Most of the  complexity seems to come from checking the number of given arguments vs parameters. Would it be that bad to leave out that check? If I remember correctly though, having wrong number of args is quite a common mistake, so I am not sure . I think if  `inspect.signature` does not initially raise exception (as you say will have to add some error handling for that), then the check for variable args is fairly robust. Another thing to note IIRC is that most of the code written by students in M269 will not have variable number args.

2025-01-03 14:02 UTC, mwermelinger commented
Good point about making explicit that no tests were run if any one is invalid. However, it still remains the case that tests with wrong number of args will be treated differently, depending on args being fixed (invalid test) or variable (test crashes, making `test()` crash). Therefore I think it's best to always consider wrong argument number as a test failure. We can still have a more user-friendly message for the fixed args case, instead of catching an exception, but it's easier to draw the invalid/failed line if we only check that it's a tuple/list with at least a string and an expected output.

2025-01-06 17:55 UTC, densnow commented
The code in this PR is doing roughly the following.

1. Check if the test table is a list or a tuple, if it isn't, exit the function and display appropriate message (including that the function has not been fully tested). 
2.  Check if the function to be tested is a built-in, if it is, exit with appropriate message. 
3. For each test case in the table test do the following checks:
    1. If it is not a list or tuple, add appropriate message to the errors.
    2. Otherwise if it does not have a string as the first item, add appropriate message to the errors.
    3. Otherwise if the function does not have a variable number of args, and the number of args doesn't match the expected number, add appropriate message to the errors.
4. If any messages have been added to the errors, display them to the user (including that the function has not been tested) and exit.
5. Otherwise, test the function with the test table.

Using the algorithm above, we are providing accurate messages to the user about which test cases are invalid and why. This is the  all or nothing approach, where a single invalid test case means the function is not tested. How do you wish to change this approach?

Using `inspect.signature` means that the self argument is not counted, so no need to distinguish between methods and functions as originally planned. This fixes the original issue. 

If a function has a variable number of args, then we can only provide lower bounds for the expected number of args . For some cases like when the variable arguments are default arguments, we can also provide an upper bounds for the expected arguments, but this could be further increasing the complexity of this simple test function!

2025-01-10 00:00 UTC, densnow commented
Looking at this again and re-reading your original comment, I don't think it would be that bad to catch exceptions from test cases when they are being run. In doing so, we could either stop all testing and report the exceptions with a more user friendly message, or, as you originally said, print passed, failed and invalid. In the testing part of the function we would just need to collect messages and exceptions instead of printing them right away.

I don't see a reason to remove the existing checks. They will catch most of the invalid cases before they are run and provide clearer messaging as to why they are invalid. The ones that get through will mostly be for functions with variable numbers of arguments, and of course other errors we have not thought of. At this point we can still report the name of the test case because we will have confirmed that it has a string as first element.

2025-02-14 14:36 UTC, mwermelinger commented
Apologies for the long silence. I've made some changes, click the ... next to commit 4dc317d above. I've already checked against the notebooks in the docs. Could you check with Exercise 9.5.2 in the book, which started it all? Thanks.

2025-02-14 18:16 UTC, mwermelinger approved these changes

2025-02-14 18:24 UTC, merged